auto-sync: master commit a8d828aa16caee6d7c9d48957cb79660c1484289

diff --git a/3.8/test/run b/3.8/test/run
--- a/3.8/test/run
+++ b/3.8/test/run
@@ -187,15 +187,11 @@ test_application() {
   cleanup_app
 }
 
-test_latest_imagestreams() {
-  local result=1
-  info "Testing the latest version in imagestreams"
-  # Switch to root directory of a container
-  pushd "${test_dir}/../.." >/dev/null || return 1
-  ct_check_latest_imagestreams
-  result=$?
-  popd >/dev/null || return 1
-  check_result $result
+test_from_dockerfile(){
+  info "Test from Dockerfile"
+  sed "s@#IMAGE_NAME#@${IMAGE_NAME}@" $test_dir/from-dockerfile/Dockerfile.tpl > $test_dir/from-dockerfile/Dockerfile
+  ct_test_app_dockerfile $test_dir/from-dockerfile/Dockerfile 'https://github.com/sclorg/django-ex.git' 'Welcome to your Django application on OpenShift' app-src
+  check_result $?
 }
 
 # Since we built the candidate image locally, we don't want S2I attempt to pull
@@ -234,10 +230,24 @@ for app in ${@:-${WEB_APPS[@]}}; do
   # test application with init wrapper
   CONTAINER_ARGS="-e ENABLE_INIT_WRAPPER=true" test_application
 
-  test_latest_imagestreams
-
   info "All tests for the ${app} finished successfully."
   cleanup ${app}
 done
+
+if [ "$OS" == "rhel7" ] || [ "$OS" == "centos7" ]; then
+   # autocleanup only enabled here as only the following tests so far use it
+   CID_FILE_DIR=$(mktemp -d)
+   ct_enable_cleanup
+
+   info "Testing variable presence during \`docker exec\`"
+   ct_check_exec_env_vars
+   check_result $?
+
+   info "Checking if all scl variables are defined in Dockerfile"
+   ct_check_scl_enable_vars
+   check_result $?
+fi
+
+test_from_dockerfile
 
 info "All tests finished successfully."
